/*

 INICIAL.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : keyboard.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define inicialWidth 20
#define inicialHeight 18
#define inicialBank 0

extern unsigned char inicial[];

/* End of INICIAL.H */
