/*

 BLACKMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\henri\Desktop\Nova pasta (5)\led.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define blackmapWidth 20
#define blackmapHeight 18
#define blackmapBank 0

extern unsigned char blackmap[];

/* End of BLACKMAP.H */
